### ISSUE TITLE
`@service` decorator doesn't work with ember 3.10.0

### ISSUE THREAD

**Issue by devdemi** [ember-decorators/ember-decorators#444]
I have tiny component:
```
import Component from '@ember/component';
import { inject as service } from '@ember-decorators/service';

export default class Switcher extends Component {

    @service i18n;

    init() {
        super.init(...arguments);
        if(!this.options) {
            let options = [
                { title: this.i18n.t('application.yes'), value: 1 },
                { title: this.i18n.t('application.no'), value: 0 }
            ];

            this.set('options', options);
        }
    }
}
```
During rendering the component next error occurred:
`Uncaught (in promise) TypeError: Cannot read property 't' of undefined`
Before `Ember` was updated to `3.10` it works well.

**Comment by artemgurzhii** [comment]
@devdemi What version of `ember-decorators` are you using? 

Since [v6.0.0](https://github.com/ember-decorators/ember-decorators/releases/tag/v6.0.0) package `@ember-decorators/service` is removed in favor of vanilla `import { inject as service } from '@ember/service';`

**Comment by devdemi** [comment]
@artemgurzhii Yes, I read about this but we still use `v5.2.0`

**Comment by buschtoens** [comment]
It _could_ very well be that Ember 3.10 is not compatible with the `ember-decorators@5.*` series.

**Comment by devdemi** [comment]
I upgraded `ember-decorators` to `v6.0.0` and start to get the error:
`TypeError: (0 , decorators[i]) is not a function`
I have 
`ember-cli-babel v7.7.3`
`babel-eslint v10.0.1`
`ember-source v3.10.0`
Also I changed  `@ember-decorators/service` with vanilla `@ember/service`

**Comment by artemgurzhii** [comment]
@devdemi Have you installed [ember-decorators-polyfill](https://github.com/pzuraq/ember-decorators-polyfill)?

**Comment by devdemi** [comment]
@artemgurzhii but I read in the documentation of `ember-decorators-polyfill`
`This addon is not needed in Ember 3.10+`

**Comment by pzuraq** [comment]
@devdemi have you removed `@ember-decorators/babel-transforms` as well? Ember Decorators v6 is not compatible with the old transforms.

**Comment by dev-zetta** [comment]
I can confirm this. Same error. Service is not bing injected. It doen't exists and return undefined.

**Comment by dev-zetta** [comment]
Ok, I just found out that this his something to do with flow plugin. After removing plugin from the plugins definition, the service gets injected. However I still have the probblem with action decorator not being found in the package.

```
    babel: {
      debug: true,
      //loose: false,
      //useBuiltIns: 'entry',
      //modules: false,
      plugins: [
        "@babel/plugin-transform-flow-strip-types" // this caused the service bug
      ]
    },
```
